--Creates the database
CREATE DATABASE "ENC_Earthquake_Email_List"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
--Creates the table that holds the emails
CREATE TABLE public.emails
(
	--Emails to be stored as Text
    email text COLLATE pg_catalog."default" NOT NULL,
    
	--id number to be stored as an integer (primary key)
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT emails_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.emails
    OWNER to postgres;